name: 'build-test'
on: # rebuild any PRs and main branch changes
  repository_dispatch:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    # runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: |
          ls -la
      - uses: ./
        with:
          milliseconds: 1000
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_BASE_URL: 'https://enterprisedb.atlassian.net'
